# Generated by Django 4.2 on 2025-06-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceslide',
            name='link',
            field=models.URLField(blank=True, default='#', max_length=500, verbose_name='Ссылка'),
        ),
    ]
