# Generated by Django 4.2 on 2025-06-26 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_serviceslide_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название галереи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-тег')),
                ('tag_type', models.CharField(choices=[('global', 'Глобальный'), ('basic', 'Базовый')], default='basic', max_length=10, verbose_name='Тип тега')),
                ('show_in_menu', models.BooleanField(default=False, verbose_name='Показывать в меню')),
                ('menu_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название в меню')),
                ('menu_order', models.PositiveIntegerField(default=0, verbose_name='Порядок в меню')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['menu_order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Основной контент')),
                ('is_home', models.BooleanField(default=False, verbose_name='Главная страница')),
                ('show_slider', models.BooleanField(default=False, verbose_name='Показывать слайдер')),
                ('show_in_menu', models.BooleanField(default=False, verbose_name='Показывать в меню')),
                ('menu_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название в меню')),
                ('menu_order', models.PositiveIntegerField(default=0, verbose_name='Порядок в меню')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_service', models.BooleanField(default=False, verbose_name='Является услугой')),
                ('tags', models.ManyToManyField(blank=True, to='services.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['menu_order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.gallery')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Изображения галереи',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery', to='services.page'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='tag',
            field=models.ForeignKey(blank=True, limit_choices_to={'tag_type': 'basic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.tag', verbose_name='Базовый тег'),
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока')),
                ('content', models.TextField(verbose_name='Содержимое блока')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='services.page')),
            ],
            options={
                'verbose_name': 'Блок контента',
                'verbose_name_plural': 'Блоки контента',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='request',
            name='service',
            field=models.ForeignKey(limit_choices_to={'is_service': True}, on_delete=django.db.models.deletion.CASCADE, to='services.page', verbose_name='Услуга'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
