# Generated by Django 5.2.3 on 2025-06-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_gallery_tag_page_galleryimage_gallery_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержимое блока'),
        ),
    ]
