# Generated by Django 5.2.3 on 2025-06-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_contentblock_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='content',
            field=models.TextField(verbose_name='Содержимое блока'),
        ),
    ]
